# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hsarhan <hassanAsarhan@outlook.com>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/03/27 18:38:35 by hsarhan           #+#    #+#              #
#    Updated: 2022/03/27 18:41:16 by hsarhan          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all: fclean rush-02

rush-02:
	gcc -Werror -Wall -Wextra -o rush-02 utility.c utility2.c convert.c dict.c main.c

fclean:
	rm -f rush-02
